core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),

    path('search/', views.search, name='search'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('', views.items, name='items'),
]

project/urls.py
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('', views.projects, name='projects')
]

vpolitakis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('projects/', include('project.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

class FiringType(models.Model):
    COLOR_CHOICES = (
    ('gray-100','gray-100'),
    ('white', 'white'),
)

    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="media", blank=True, null=True, max_length=255)
    color = models.CharField(max_length=255, choices=COLOR_CHOICES, null=True)
    

    def __str__(self):
        return self.name
    
class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    subject = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return self.name

item/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta():
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Item(models.Model):
    SHAPE_CHOICES = (
    ('Amphora','Amphora'),
    ('Stirrup_Jar', 'Stirrup Jar'),
    ('Jug','Jug'),
    ('Cup','Cup'),
    ('Mug','Mug'),
    ('Rhyton','Rhyton'),
    ('Figure','Figure'),
    ('Strainer','Strainer'),
    ('Spouted_Jar','Spouted Jar'),
    ('Ewer','Ewer'),
    ('Flask','Flask'),
)
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media', blank=True, null=True, max_length=255)
    image1 = models.ImageField(upload_to='media', blank=True, null=True, max_length=255)
    image2 = models.ImageField(upload_to='media', blank=True, null=True, max_length=255)
    image3 = models.ImageField(upload_to='media', blank=True, null=True, max_length=255)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.PositiveIntegerField()
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    shape = models.CharField(max_length=255, choices=SHAPE_CHOICES, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    

    def Meta():
        ordering=('created_at',)

    def __str__(self):
        return self.name

project/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta():
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Project(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='media', max_length=255)
    collab = models.CharField(max_length=255, blank=True)
    location = models.CharField(max_length=255, null=True, blank=True)
    category = models.ForeignKey(Category, related_name='projects', on_delete=models.CASCADE, default=None)
    description = models.TextField(blank=True, null=True)
    date = models.CharField(max_length=255, blank=True, null=True)


    def __str__(self):
        return self.name

    # PROJECT_CATEGORIES = (
    #     ('Experimental', 'Experimental'),
    #     ('Seminars', 'Seminars'),
    #     ('Theories', 'Theories'),
    #     ('Activities', 'Activities'),
    #     ('Collaborations', 'Collaborations'),
    # )

core/forms.py
from django.forms import ModelForm
from .models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from project.models import Project
from .models import FiringType
from django.db.models import Q
from core.forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.

def search(request):
    query = request.GET.get('query', '')

    if query:
        items = Item.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
        projects = Project.objects.filter(Q(name__icontains=query) | Q(description__icontains=query) | Q(location__icontains=query))

    return render(request, 'core/search.html', {
        'query':query,
        'items':items,
        'projects':projects,

    })

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'core/success.html')
    form = ContactForm()
    context = {'form': form}
    return render(request, 'core/contact.html', context)


def index(request):
    #get the last 4 of the list
    items1 = Item.objects.filter(is_sold=False)
    items = items1[len(items1)-4:]
    categories = Category.objects.all()
    firingtype = FiringType.objects.all()
    projects1 = Project.objects.all()
    projects = projects1[len(projects1)-4:]
    
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
        'firingtype': firingtype,
        'projects': projects,
    })

item/views.py
from django.shortcuts import render, get_object_or_404
from .models import Item, Category
from django.db.models import Q, Max

# Create your views here.

def items(request):
    shape_choices = Item.SHAPE_CHOICES
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    shape_id = request.GET.get('shape', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)
    min_price = request.GET.get('min_price', 0)
    max_price = request.GET.get('max_price', 0)

    if min_price:
        items = items.filter(price__gte=int(min_price))

    if max_price:
        items = items.filter(price__lte=int(max_price))

    if shape_id:
        items = items.filter(shape=shape_id)

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))


    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
        'shape_id': shape_id,
        'shape_choices': shape_choices,
        'min_price': min_price,
    })

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    similar = Item.objects.filter(is_sold=False, category=item.category).exclude(pk=pk)[0:4]
    # filter(category=item.category)

    return render(request, 'item/detail.html', {
        'item': item,
        'similar': similar,
    })

project/views.py
from django.shortcuts import render, get_object_or_404
from .models import Project, Category
from django.db.models import Q

# Create your views here.

def projects(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    projects = Project.objects.all()

    if category_id:
        projects = projects.filter(category_id=category_id)

    if query:
        projects = projects.filter(Q(name__icontains=query) | Q(collab__icontains=query) | Q(location__icontains=query) | Q(description__icontains=query))

    return render(request, 'project/projects.html',{
        'projects': projects,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })


def detail(request, pk):
    project = get_object_or_404(Project, pk=pk)
    similar = Project.objects.filter(category=project.category).exclude(pk=pk)[0:4]
    # filter(category=item.category)

    return render(request, 'project/detail.html', {
        'project': project,
        'similar': similar,
    })

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        .slides { width: 100%; }
        .slides-hidden { display : none; }
        
</style>

    </style>
    <title>{% block title %}{% endblock title %} | V. Politakis</title>
</head>
<body>
    <!-- full body -->
    <div> 
        <!-- navigator -->
        <div class="border-b p-4 sticky top-0 z-50 bg-white">
            <nav class="flex flex-wrap items-center">
                <a href="/">
                    <h1 class="font-semibold p-2 text-orange-900 text-lg">Vassilis Politakis</h1>
                </a>
                <div class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 p-2 border-2">
                    <form action="{% url 'core:search' %}">
                        <input type="text" name="query" value="{{ query }}" placeholder="Search in Website" class="">
                        <button>&#10061;</button>
                    </form>
                    

                </div>
                <div class="absolute right-0 space-x-4 items-center text-lg">
                    <!-- quick buttons -->
                    <a href="/contact/" class="hover:text-orange-800">Contact</a>
                    <a href="#" class="text-orange-900 hover:text-orange-800 hover:scale-110">About</a>
                    <a href="{% url 'project:projects' %}" class="bg-white hover:bg-gray-200 text-orange-900 border-2 border-orange-900 p-2 rounded-lg bg-opacity-70">Projects</a>
                    <a href="{% url 'item:items' %}" class="bg-orange-800 hover:bg-orange-700 text-white p-2 rounded-lg">Products</a>
                </div>
                
            </nav>
        </div>
            
        

        <div class="bg-gray-50">
            <!-- content -->
            {% block content %}
            {% endblock content %}
        </div>

        <footer class="flex justify-between bg-gray-200 mt-5 pl-52 pr-52 pt-10 pb-10">
            <!-- footer -->
            <div>
                <h4 class="font-semibold mb-2">About</h4>
                <em class="flex w-1/2 text-orange-900">Vassilis Politakis was born in Heraklion Crete in 1965. Since 1990 he has worked to understand and recreate the pottery of the Aegean and Cypriot bronze age.</em>
            </div>
            <div>
                <h5 class="font-semibold mb-2">Menu</h5>
                <ul class="text-orange-900">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                    <li>    
                        <a href="#">Privacy Policy</a>
                    </li>
                    <li>    
                        <a href="#">Terms of Use</a>
                    </li>
                </ul>
            </div>
        </footer>
    </div>
</body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
    <div class="flex justify-center font-serif text-xl text-bold aspect-w-1" >
        <!-- header -->
        <header class="relative">
            <img src="/media/banner2-small.jpg" alt="banner">
                    <!-- <video class="object-cover h-52 w-full" autoplay muted loop>
                        <source src="/media/dad_wheel.mp4" type="video/mp4"> 
                    </video> -->
            <!-- heading text -->
            <div class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-white">
                <h3 class="p-1">Let <em>minoan pottery</em> </h3>
                <h3 class="ml-5 p-1">speak to your heart</h3>
            </div>
        </header>
    </div>

    <div class="2xl:mx-40 lg:mx-30 md:mx-10 sm:mx-0">
        <div class="ml-10 mr-10 ">
            <!-- short bio -->
            <div class="px-6 pt-8 font-serif ">
                <div class="w-full flex justify-center">
                    <div class="flex items-center relative mx-20 ">
                        <img class="h-72 rounded-full shadow-xl" src="/media/vassilis.jpg" alt="vassilis politakis wheel">
                        <p class="ml-8 leading-normal text-gray-900 text-3xl">Since 1990, <strong>Vassilis Politakis</strong><br>has worked to understand and recreate<br>the <strong>pottery of the Aegean and Cypriot bronze age.</strong><br><br>His expertise is supported by collaborations with:</p>
                    </div>                    
                </div>
                <div class="bg-gray-200 rounded-xl p-5 mt-5 mb-5 ">
                    <p class="whitespace-pre-wrap leading-10 text-center italic">The British&nbsp;School&nbsp;at&nbsp;Athens (BSA)            The&nbsp;Italian&nbsp;arch.&nbsp;school            The&nbsp;American&nbsp;Study&nbsp;Center&nbsp;of&nbsp;Aegean&nbsp;Prehistory&nbsp;(INSTAP-EC)          The&nbsp;Heraklion&nbsp;Archaeological&nbsp;Museum            The&nbsp;Official&nbsp;Hellenic&nbsp;Institute&nbsp;of&nbsp;Material&nbsp;Science&nbsp;(Demokritos)            The&nbsp;University&nbsp;of&nbsp;Crete         The&nbsp;Greek&nbsp;Ministry&nbsp;of&nbsp;Culture           And&nbsp;several&nbsp;individual&nbsp;academic&nbsp;archaeologists</p>
                </div>
            </div>
        </div>
    </div>

    <div>
        <!-- latest pieces -->
        <div class="2xl:mx-96 sm:mx-0 md:mx-20 border-t-2 border-gray-100">
            <div class="px-6 py-12 rounded-xl">
                <h2 class="mb-8 leading-normal text-gray-900 text-3xl font-serif text-center">Latest Pieces</h2>
                <div class="mb-8">
                    <h2 class="italic font-serif font-light text-xl text-center text-orange-800 p-2">100% <em>hand-made</em> & <em>hand-painted</em></h2>
                </div>
                <div class="grid grid-cols-4 gap-3">
                    {% for item in items %}
                        <div class="relative shadow-lg bg-gray-100 m-2 hover:scale-90">
                            <a href="{% url 'item:detail' item.id %}">
                                <div>
                                    <img class="" src="{{ item.image.url }}">
                                </div>
                                <div class="p-2 bg-gray-100">
                                    <h2 class="xl:text-xl lg:text-lg md:text-md sm:text-sm font-semibold">{{ item.name }}</h2>
                                    <p class="text-gray-500 text-sm py-2">Created on {{ item.created_at }}</p>
                                </div>
                            </a>
                            <a href="{% url 'item:items' %}?query={{ query }}&category={{ item.category.id }}">
                                <div class="absolute top-0 right-0 p-2 bg-orange-800 text-white m-1 rounded-full text-xs bg-opacity-70 hover:bg-opacity-100">{{ item.category }}</div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
                <div class="flex justify-center">
                    <a href="items/" class="bg-orange-900 p-2 rounded-xl text-white hover:bg-orange-800 mt-5 px-5 bg-opacity-90">View More Products</a>
                </div>
            </div>
        </div>
    </div>

    <div>
        <!-- projects -->
        <div class="2xl:mx-96 sm:mx-0 md:mx-20 border-t-2 border-b-2 border-gray-100">
            <div class="px-6 py-12">
                <h2 class="mb-12 leading-normal text-gray-900 text-3xl font-serif text-center">Latest Projects</h2>
                <div class="grid grid-cols-4 gap-3">
                    {% for project in projects %}
                        <div class="relative shadow-lg bg-gray-100 m-2 hover:scale-90">
                            <a href="{% url 'project:detail' project.id %}">
                                <div>
                                    <img class="" src="{{ project.image.url }}">
                                </div>
                                <div class="p-2">
                                    <h2 class="xl:text-xl lg:text-lg md:text-md sm:text-sm font-semibold">{{ project.name }}</h2>
                                    {% if project.collab %}
                                        <h3 class="text-gray-500 text-sm py-2">In collaboration with <strong>{{ project.collab }}</strong></h3>
                                    {% endif %}
                                    {% if project.location %}
                                    <h3 class="text-gray-500 text-sm">Located in <strong>{{ project.location }}</strong> </h3>
                                    {% endif %}
                                </div>
                            </a>
                            <a href="{% url 'project:projects' %}?query={{ query }}&category={{ project.category.id }}">
                                <div class="absolute top-0 right-0 p-2 bg-orange-800 text-white m-1 rounded-full text-xs bg-opacity-80 hover:bg-opacity-100">{{ project.category }}</div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
                <div class="flex justify-center">
                    <a href="projects/" class="bg-orange-900 p-2 rounded-xl text-white hover:bg-orange-800 mt-5 px-5 bg-opacity-90">View More Projects</a>
                </div>
            </div>
        </div>
    </div>

    <h2 class="my-5 leading-normal text-gray-900 text-3xl font-serif text-center">Types of Techniques Used</h2>
    {% for type in firingtype %}
        <div class="px-6 py-10  bg-{{type.color}}">
            <div class="2xl:mx-96 sm:mx-0 md:mx-20">
                <div class="flex items-center space-x-20 relative">
                    <div class="w-1/3">
                        <h2 class="text-5xl">{{ type.name }}</h2>
                    </div>
                    <div class="w-full leading-10 font-serif">
                        <p>
                            {{type.description|linebreaks}}
                        </p>
                    </div>
                    <div class="flex w-1/5 top-0">
                        <section class="">
                            <img class="h-50 w-auto" src="{{type.image.url}}">
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    <div class="2xl:mx-96 sm:mx-0 md:mx-20 border-t-2 border-gray-100">
        <!-- workshop, store, e-eshop -->
        <div class="grid grid-cols-2 gap-2 font-serif">
            <div class="col-span-1 p-10 space-y-5">
                <h2 class="leading-normal text-gray-900 text-3xl font-serif text-center font-bold">Workshop</em></h2>
                <div class=" font-sans space-y-3">
                    <p class="italic text-gray-800 text-center">Arch. Evgeniou 17, Heraklion, Crete<br><strong>Greece</strong></p>
                    <p class="italic text-gray-800 text-center"><strong>Mob.</strong>+30 6938 535 125</p>
                    <p class="italic text-gray-800 text-center"><strong>Email </strong>info@spiritofgreece.gr</p>
                </div>
                <img src="/media/workshop.jpg" alt="" class="rounded-xl">
            </div>
            <div class="col-span-1 p-10 space-y-5">
                <h2 class="leading-normal text-gray-900 text-3xl font-serif text-center font-bold">Store</em></h2>
                <div class=" font-sans space-y-3">
                    <p class="italic text-gray-800 text-center">Papa Alexandrou 4, Heraklion, Crete<br><strong>Greece</strong></p>
                    <p class="italic text-gray-800 text-center"><strong>Tel.</strong>+30 2810 286 287</p>
                    <p class="italic text-gray-800 text-center"><strong>Email </strong>info@spiritofgreece.eu</p>
                </div>
                <img src="/media/store.jpg" alt="" class="rounded-xl">
            </div>
        </div>
    </div>


{% endblock content %}
    

core/templates/core/search.html
{% extends 'core/base.html' %}

{% block title %}Search {{query}}{% endblock title%}

{% block content %}
    <h2 class="mb-8 text-2xl text-center mt-10">Search Results</h2>
    {% if items|length == 0 and projects|length == 0 %}
    <h2 class="mb-8 text-2xl ml-20">No results</h2>
    {% endif %}

    {% if items|length > 0 %}
        <div class="2xl:mx-96 sm:mx-0 md:mx-20 border-t-2 border-gray-100">
            <div class="px-6 py-12 rounded-xl">
                <h2 class="mb-8 text-2xl ml-20">Products</h2>
                <div class="grid grid-cols-4 gap-3">
                    {% for item in items %}
                        <div class="relative shadow-lg bg-gray-100 m-2 hover:scale-90">
                            <a href="{% url 'item:detail' item.id %}">
                                <div>
                                    <img class="" src="{{ item.image.url }}">
                                </div>
                                <div class="p-2 bg-gray-100">
                                    <h2 class="xl:text-xl lg:text-lg md:text-md sm:text-sm font-semibold">{{ item.name }}</h2>
                                    <p class="text-gray-500 text-sm py-2">Created on {{ item.created_at }}</p>
                                </div>
                            </a>
                            <a href="{% url 'item:items' %}?query={{ query }}&category={{ item.category.id }}">
                                <div class="absolute top-0 right-0 p-2 bg-orange-800 text-white m-1 rounded-full text-xs bg-opacity-70 hover:bg-opacity-100">{{ item.category }}</div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
                <div class="flex justify-center">
                    <a href="{% url 'item:items' %}" class="bg-orange-900 p-2 rounded-xl text-white hover:bg-orange-800 mt-5 px-5 bg-opacity-90">View More Products</a>
                </div>
            </div>
        </div>
    {% endif %}
    
    {% if projects|length > 0 %}
        <div class="2xl:mx-96 sm:mx-0 md:mx-20 border-t-2 border-b-2 border-gray-100">
            <div class="px-6 py-12">
                <h2 class="mb-12 text-2xl ml-20">Projects</h2>
                <div class="grid grid-cols-4 gap-3">
                    {% for project in projects %}
                        <div class="relative shadow-lg bg-gray-100 m-2 hover:scale-90">
                            <a href="{% url 'project:detail' project.id %}">
                                <div>
                                    <img class="" src="{{ project.image.url }}">
                                </div>
                                <div class="p-2">
                                    <h2 class="xl:text-xl lg:text-lg md:text-md sm:text-sm font-semibold">{{ project.name }}</h2>
                                    {% if project.collab %}
                                        <h3 class="text-gray-500 text-sm py-2">In collaboration with <strong>{{ project.collab }}</strong></h3>
                                    {% endif %}
                                    {% if project.location %}
                                    <h3 class="text-gray-500 text-sm">Located in <strong>{{ project.location }}</strong> </h3>
                                    {% endif %}
                                </div>
                            </a>
                            <a href="{% url 'project:projects' %}?query={{ query }}&category={{ project.category.id }}">
                                <div class="absolute top-0 right-0 p-2 bg-orange-800 text-white m-1 rounded-full text-xs bg-opacity-80 hover:bg-opacity-100">{{ project.category }}</div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
                <div class="flex justify-center">
                    <a href="{% url 'project:projects' %}" class="bg-orange-900 p-2 rounded-xl text-white hover:bg-orange-800 mt-5 px-5 bg-opacity-90">View More Projects</a>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock content %}

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="2xl:mx-52 md:mx-10 sm:mx-0 my-10">
    <div class="border-b-2 ">
        <div class="grid grid-cols-5 gap-6 mb-10">
            <div class="col-span-3 border-2 border-orange-900 flex justify-center">
                <img src="{{ item.image.url }}" class="rounded-xl">
            </div> 

            <div class="col-span-2 bg-gray-100 rounded-xl p-10">
                <h1 class="text-xl font-semibold">{{ item.name }}</h1>
                <div class="my-10">
                    <p>{{ item.description|linebreaks }}</p>
                </div>
                <h3 class="">Price: <strong>{{ item.price }}€</strong></h3>
                <a class="mt-10 inline-block text-xl text-white bg-orange-800 hover:bg-orange-700 p-3 rounded-xl" href="">Contact</a>
            
            </div>
        </div>
        

        <div>
            {% if item.image1 %}
                <img src="{{ item.image1.url }}" alt="item_image_1" onclick="change(this.src)">
            {% endif %}
            {% if item.image2 %}
                <img src="{{ item.image2.url }}" alt="item_image_1" onclick="change(this.src)">
            {% endif %}
            {% if item.image3 %}
                <img src="{{ item.image3.url }}" alt="item_image_1" onclick="change(this.src)">
            {% endif %}
        </div>
    </div>


    <h2 class="text-center text-2xl my-10">Similar Products</h2>
    <div class="grid grid-cols-4 gap-6 border-gray-50">
        {% for s in similar %}
                        <div class="relative shadow-lg bg-gray-100 m-2 hover:scale-90">
                            <a href="{% url 'item:detail' s.id %}">
                                <div>
                                    <img class="" src="{{ s.image.url }}">
                                </div>
                                <div class="p-2 bg-gray-100">
                                    <h2 class="xl:text-xl lg:text-lg md:text-md sm:text-sm font-semibold">{{ s.name }}</h2>
                                    <p class="text-gray-500 text-sm py-2">Created on {{ s.created_at }}</p>
                                </div>
                            </a>
                            <a href="#">
                                <div class="absolute top-0 right-0 p-2 bg-orange-800 text-white m-1 rounded-full text-xs bg-opacity-70 hover:bg-opacity-100">{{ s.category }}</div>
                            </a>
                        </div>
                    {% endfor %}

    </div>
</div>

{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}Products{% endblock title %}

{% block content %}
    <div class="grid grid-cols-4 gap-4">
        <div class="col-span-1 pl-5"> 
            <form method="get" action="{% url 'item:items' %}">
                <input name="query" class="w-full my-3 py-4 px-6 border roundend-xl" type="text" value="{{ query }}" placeholder="Search in Products">

                <button class="py-4 px-8 text-lg bg-orange-800 text-white rounded-xl" >Search</button>
            

                <hr class="my-6">

                <p class="font-semibold text-lg">Categories</p>

                <ul>
                    {% for category in categories %}
                        <li class="py-2 px-2 rounded-xl {% if category.id == category_id %} bg-orange-800 bg-opacity-50{% endif %}">
                            <a href="{% url 'item:items' %}?query={{ query }}{% if shape %} &shape={{ shape }}{% endif %}&category={{ category.id }}" class="text-lg">{{ category.name }}</a>
                        </li>
                    {% endfor %}
                </ul>

                <hr class="my-6">

                <p class="font-semibold text-lg">What shape are you looking for?</p>

                <ul>
                    {% for shape, text in shape_choices %}
                    <li class="py-2 px-2 rounded-xl {% if shape == shape_id %} bg-red {% endif %}">
                        <a href="{% url 'item:items' %}?query={{ query }}&shape={{ shape }}">{{text}}</a>
                    </li>
                    {% endfor %}
                </ul>

                <hr class="my-6">

                <p class="font-semibold text-lg">Price</p>

                    Minimum: <input name="min_price" class="my-2 py-2 px-2 border round
                    end-xl" type="text" value="{{ min_price }}" placeholder="Min Price"> €
                    Maximum: <input name="max_price" class="my-2 py-2 px-2 border roundend-xl" type="text" value="{{ max_price }}" placeholder="Max Price"> €

                    <button class="py-2 mt-2 px-8 text-lg bg-orange-800 text-white rounded-xl">Apply</button>
            </form>


            <p class="font-semibold mt-6">Clear Filters</p>

            <ul>
                <li>
                    <a href="{% url 'item:items' %}" class="mt-2 py-2 px-8 inline-block bg-gray-400 text-white rounded-xl">Clear</a>
                </li>
            </ul>
        </div>

        <div class="col-span-3 bg-gray-100 ">
            <div class="py-10">
                <div class="2xl:mx-30 xl:mx-20 md:mx-10 sm:mx-0">
                    <div class="rounded-xl">
                        <div class="grid grid-cols-4 gap-5 ">
                            {% for item in items %}
                                <div class="relative shadow-lg bg-white">
                                    <a href="{% url 'item:detail' item.id %}">
                                        <div>
                                            <img class="" src="{{ item.image.url }}">
                                        </div>
                                        <div class="p-6 bg-white">
                                            <h2 class="xl:text-xl lg:text-lg md:text-md sm:text-sm">{{ item.name }}</h2>
                                            <p class="text-sm text-gray-500 pt-2">Price <strong>{{ item.price }}€</strong></p>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="absolute top-0 right-0 p-2 bg-orange-800 text-white m-1 rounded-full text-xs bg-opacity-70">{{ item.category }}</div>
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}